import { cpSync, readFileSync, rmSync } from 'node:fs'
import { resolve } from 'node:path'
import { URL, fileURLToPath } from 'node:url'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { type Plugin, defineConfig, loadEnv } from 'vite'
import { generateLlmsOutput } from './scripts/build-llms'

const here = fileURLToPath(new URL('.', import.meta.url))

/**
 * Vite's publicDir must exist before startup, and the LLM output is generated
 * separately, so each build assembles a single served directory here:
 * the checked-in `public/` assets plus the generated Markdown.
 */
const SERVED_DIR = resolve(here, '.build-public')

function prepareServedDir(): void {
  rmSync(SERVED_DIR, { recursive: true, force: true })
  cpSync(resolve(here, 'public'), SERVED_DIR, { recursive: true })
}

/**
 * Version comes from the frontend manifest (one source of truth), with a
 * fallback to the site's own version when the docs are built standalone
 * (e.g. inside the Containerfile, where the app manifest is not in context).
 */
function resolveVersion(): string {
  if (process.env.DOCS_APP_VERSION) return process.env.DOCS_APP_VERSION
  try {
    const appPkg = JSON.parse(readFileSync(resolve(here, '..', '..', 'app', 'package.json'), 'utf8'))
    return String(appPkg.version)
  } catch {
    const own = JSON.parse(readFileSync(resolve(here, 'package.json'), 'utf8'))
    return String(own.version)
  }
}

/**
 * Injects branding/OG values into index.html. The Open Graph image is
 * always `og-image.png` (generated by `scripts/og-image.ts`).
 */
function brandingPlugin(siteName: string, siteUrl: string): Plugin {
  return {
    name: 'tasky-branding',
    transformIndexHtml(html) {
      return html
        .replaceAll('%SITE_NAME%', siteName)
        .replaceAll('%SITE_URL%', siteUrl.replace(/\/$/, ''))
        .replaceAll('%OG_IMAGE%', 'og-image.png')
    },
  }
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, here, 'VITE_')
  const siteName = env.VITE_APP_SITE_NAME || 'tasky'
  const siteUrl = env.VITE_SITE_URL || 'https://docs.tasky.example'

  // Generated Markdown lands in the served dir before copying it in.
  prepareServedDir()
  generateLlmsOutput(SERVED_DIR)

  return {
    base: './',
    publicDir: SERVED_DIR,
    plugins: [react(), tailwindcss(), brandingPlugin(siteName, siteUrl)],
    define: {
      __APP_VERSION__: JSON.stringify(resolveVersion()),
    },
    build: {
      outDir: 'dist',
      sourcemap: false,
    },
  }
})
